:: =============================================================================
:: Script: creatingemptyfiles.bat
::
:: Description:
::     Generates empty text files for a predefined list of movie titles during
::     construction of the movie script dataset. The script sanitizes movie
::     titles to produce valid Windows filenames before creating placeholder
::     files.
::
:: Purpose:
::     As part of the dataset preparation process for the paper
::     "Hierarchical Ordinal Framework for Automated Movie Censorship Using
::     Full-Length Scripts" (IEEE GCAT 2025), standardized filenames were
::     required before collecting screenplay text. This utility automates the
::     creation of placeholder files while ensuring filename compatibility
::     across Windows systems.
::
:: Functionality:
::     - Creates the output directory if it does not exist.
::     - Removes or replaces invalid filename characters.
::     - Generates one empty UTF-8 text file for each movie title.
::     - Ensures consistent naming throughout dataset construction.
::
:: Inputs:
::     - List of movie titles.
::
:: Outputs:
::     - Empty movie script text files with standardized filenames.
::
:: Author:
::     Pratik N. Kalamkar
:: =============================================================================

@echo off
setlocal enabledelayedexpansion

set "G:\My Drive\PhDWorks\4_Final_Writing_Papers\05_ConferencePaper_3\dataset\Movie Scripts Corpus kaggle\screenplay_data\data\raw_texts\2008"

:: Create directory if it doesn't exist
if not exist "%output_dir%" mkdir "%output_dir%"

:: Create a function to safely create each file
:CreateFile
set "filename=%~1"
set "filename=!filename:&=and!"
set "filename=!filename:/=-!"
set "filename=!filename:?=!"
set "filename=!filename:|=!"
set "filename=!filename:<=!"
set "filename=!filename:>=!"
set "filename=!filename:Ãª=e!"
set "filename=!filename:Ã©=e!"
set "filename=!filename:Ã =a!"
set "filename=!filename:Ã¢=a!"
set "filename=!filename:Ã®=i!"
set "filename=!filename:Ã´=o!"
set "filename=!filename:Ã»=u!"
set "filename=!filename:Ã§=c!"
set "filename=!filename:Â=!"
set "filename=!filename:¡=!"
set "filename=!filename:¿=!"
echo. > "%output_dir%\!filename!.txt"
exit /b

:: Create all files by calling the function for each title
call :CreateFile "The Brothers Bloom"
call :CreateFile "Burn After Reading"
call :CreateFile "Changeling"
call :CreateFile "The Curious Case of Benjamin Button"
call :CreateFile "Deception"
call :CreateFile "Eagle Eye"
call :CreateFile "Frozen River"
call :CreateFile "Hancock"
call :CreateFile "Hellboy II The Golden Army"
call :CreateFile "How to Lose Friends and Alienate People"
call :CreateFile "Kung Fu Panda"
call :CreateFile "Marley and Me"
call :CreateFile "Max Payne"
call :CreateFile "Milk"
call :CreateFile "Mirrors"
call :CreateFile "The Other Boleyn Girl"
call :CreateFile "Pineapple Express"
call :CreateFile "Rachel Getting Married"
call :CreateFile "Revolutionary Road"
call :CreateFile "RocknRolla"
call :CreateFile "The Ruins"
call :CreateFile "Semi-Pro"
call :CreateFile "Sex and the City"
call :CreateFile "Speed Racer"
call :CreateFile "Synecdoche, New York"
call :CreateFile "Valkyrie"
call :CreateFile "The Visitor"
call :CreateFile "Wanted"
call :CreateFile "While She Was Out"
call :CreateFile "The Wrestler"
call :CreateFile "Yes Man"
call :CreateFile "In Bruges"
call :CreateFile "Indiana Jones and the Kingdom of the Crystal Skull"
call :CreateFile "Sex Drive"
call :CreateFile "Taken"
call :CreateFile "The Burrowers"
call :CreateFile "The Happening"
call :CreateFile "The House Bunny"
call :CreateFile "The Strangers"
call :CreateFile "Iron Man"
call :CreateFile "All God's Children Can Dance"
call :CreateFile "Frost-Nixon"
call :CreateFile "Happy-Go-Lucky"
call :CreateFile "I've Loved You So Long"
call :CreateFile "Luke and Brie Are on a First Date"
call :CreateFile "Street Kings"
call :CreateFile "Untraceable"
call :CreateFile "Vantage Point"
call :CreateFile "Vicky Cristina Barcelona"
call :CreateFile "Breaking Bad"
call :CreateFile "The Incredible Hulk"
call :CreateFile "Ghost Adventures"
call :CreateFile "Solstice"
call :CreateFile "The Dark Knight"
call :CreateFile "The Hurt Locker"
call :CreateFile "The Informers"
call :CreateFile "The Midnight Meat Train"
call :CreateFile "The Reader"
call :CreateFile "The Russell Girl"
call :CreateFile "Edges of Darkness"
call :CreateFile "Body of Lies"
call :CreateFile "Dr. Horrible's Sing-Along Blog"
call :CreateFile "Forgetting Sarah Marshall"
call :CreateFile "Man Overboard"
call :CreateFile "The Middleman"
call :CreateFile "The Suite Life on Deck"
call :CreateFile "WALL-E"
call :CreateFile "Cloverfield"
call :CreateFile "The Mummy Tomb of the Dragon Emperor"
call :CreateFile "17 Again"
call :CreateFile "2012"
call :CreateFile "500 Days of Summer"
call :CreateFile "District 9"
call :CreateFile "A Serious Man"
call :CreateFile "All About Steve"
call :CreateFile "Amelia"
call :CreateFile "An Education"
call :CreateFile "Angels and Demons"
call :CreateFile "Avatar"
call :CreateFile "The Blind Side"
call :CreateFile "The Boondock Saints II All Saints Day"
call :CreateFile "The Box"
call :CreateFile "Broken Embraces"
call :CreateFile "Cirque du Freak The Vampire's Assistant"
call :CreateFile "Coraline"
call :CreateFile "Parks and Recreation"
call :CreateFile "The Damned United"
call :CreateFile "The Human Centipede (First Sequence)"
call :CreateFile "Drag Me to Hell"
call :CreateFile "Extract"
call :CreateFile "Fantastic Mr. Fox"
call :CreateFile "Friday the 13th"
call :CreateFile "Funny People"
call :CreateFile "Gamer"
call :CreateFile "Triangle"
call :CreateFile "G.I. Joe The Rise of Cobra"
call :CreateFile "The Hangover"
call :CreateFile "He's Just Not That Into You"
call :CreateFile "I Love You Phillip Morris"
call :CreateFile "The Imaginarium of Doctor Parnassus"
call :CreateFile "In the Loop"
call :CreateFile "The Informant"
call :CreateFile "Inglourious Basterds"
call :CreateFile "The Invention of Lying"
call :CreateFile "Invictus"
call :CreateFile "It's Complicated"
call :CreateFile "Jennifer's Body"
call :CreateFile "The Last Station"
call :CreateFile "Law Abiding Citizen"
call :CreateFile "The Men Who Stare at Goats"
call :CreateFile "Moon"
call :CreateFile "Nine"
call :CreateFile "Ninja Assassin"
call :CreateFile "Observe and Report"
call :CreateFile "Obsessed"
call :CreateFile "Orphan"
call :CreateFile "Pandorum"
call :CreateFile "Precious"
call :CreateFile "The Proposal"
call :CreateFile "Public Enemies"
call :CreateFile "The Road"
call :CreateFile "S. Darko"
call :CreateFile "Sherlock Holmes"
call :CreateFile "The Shift"
call :CreateFile "Millionaire Slumdog"
call :CreateFile "Star Trek"
call :CreateFile "Cougar Town"
call :CreateFile "Surrogates"
call :CreateFile "Terminator Salvation"
call :CreateFile "The Ugly Truth"
call :CreateFile "Up in the Air"
call :CreateFile "Up"
call :CreateFile "Watchmen"
call :CreateFile "The White Ribbon"
call :CreateFile "Whiteout"
call :CreateFile "Year One"
call :CreateFile "3 Idiots"
call :CreateFile "Bright Star"
call :CreateFile "Enter the Void"
call :CreateFile "Night at the Museum Battle of the Smithsonian"
call :CreateFile "Planet 51"
call :CreateFile "Solitary Man"
call :CreateFile "Solomon Kane"
call :CreateFile "Sorority Row"
call :CreateFile "The Descent Part 2"
call :CreateFile "The Time Traveler's Wife"
call :CreateFile "The Young Victoria"
call :CreateFile "Under the Mountain"
call :CreateFile "X-Men Origins Wolverine"
call :CreateFile "After.Life"
call :CreateFile "Vince The Roommate from Hell"
call :CreateFile "Curse of the Cat People-Glenda and Odessa"
call :CreateFile "I Hope They Serve Beer in Hell"
call :CreateFile "A Perfect Getaway"
call :CreateFile "God's Country, Off Route 9"
call :CreateFile "The Haunting in Connecticut"
call :CreateFile "A Single Man"
call :CreateFile "American Bully"
call :CreateFile "City Island"
call :CreateFile "Crazy Heart"
call :CreateFile "Murderland"
call :CreateFile "Stoked"
call :CreateFile "The Last House on the Left"
call :CreateFile "The Messenger"
call :CreateFile "The Twilight Saga New Moon"
call :CreateFile "Where the Wild Things Are"
call :CreateFile "Balls Out Gary the Tennis Coach"
call :CreateFile "Cloudy with a Chance of Meatballs"
call :CreateFile "Harry Potter and the Half-Blood Prince"
call :CreateFile "I Love You, Man"
call :CreateFile "Mr. Nobody"
call :CreateFile "Notorious"
call :CreateFile "Splice"
call :CreateFile "The Fourth Kind"
call :CreateFile "The Hole"
call :CreateFile "The Unborn"
call :CreateFile "Downton Abbey"
call :CreateFile "127 Hours"
call :CreateFile "Resident Evil Afterlife"
call :CreateFile "The American"
call :CreateFile "The Back-up Plan"
call :CreateFile "Beginners"
call :CreateFile "Black Swan"
call :CreateFile "Blue Valentine"
call :CreateFile "The Book of Eli"
call :CreateFile "The Bounty Hunter"
call :CreateFile "Buried"
call :CreateFile "Burlesque"
call :CreateFile "Clash of the Titans"
call :CreateFile "Date Night"
call :CreateFile "Death at a Funeral"
call :CreateFile "Easy A"
call :CreateFile "Fair Game"
call :CreateFile "The Fighter"
call :CreateFile "Hesher"
call :CreateFile "Hot Tub Time Machine"
call :CreateFile "How to Train Your Dragon"
call :CreateFile "I Spit on Your Grave"
call :CreateFile "Inception"
call :CreateFile "The Kids Are All Right"
call :CreateFile "The King's Speech"
call :CreateFile "Legion"
call :CreateFile "The Losers"
call :CreateFile "Machete"
call :CreateFile "Megamind"
call :CreateFile "The Next Three Days"
call :CreateFile "Remember Me"
call :CreateFile "Scott Pilgrim vs. the World"
call :CreateFile "She's Out of My League"
call :CreateFile "The Social Network"
call :CreateFile "Tamara Drewe"
call :CreateFile "The Tourist"
call :CreateFile "Wall Street Money Never Sleeps"
call :CreateFile "The Whistleblower"
call :CreateFile "Alice in Wonderland"
call :CreateFile "Animal Kingdom"
call :CreateFile "Diary of a Wimpy Kid"
call :CreateFile "Flipped"
call :CreateFile "It's Kind of a Funny Story"
call :CreateFile "Never Let Me Go"
call :CreateFile "Percy Jackson and the Olympians The Lightning Thief"
call :CreateFile "Piranha 3D"
call :CreateFile "Prince of Persia The Sands of Time"
call :CreateFile "Rabbit Hole"
call :CreateFile "RED"
call :CreateFile "Repo Men"
call :CreateFile "Salt"
call :CreateFile "Secretariat"
call :CreateFile "Skyline"
call :CreateFile "The A-Team"
call :CreateFile "The Conspirator"
call :CreateFile "The Crazies"
call :CreateFile "The Debt"
call :CreateFile "The Expendables"
call :CreateFile "The Sorcerer's Apprentice"
call :CreateFile "The Switch"
call :CreateFile "The Town"
call :CreateFile "The Wolfman"
call :CreateFile "Unthinkable"
call :CreateFile "Valentine's Day"
call :CreateFile "Another Year"
call :CreateFile "Dear John"
call :CreateFile "F"
call :CreateFile "Jack Goes Boating"
call :CreateFile "MacGruber"
call :CreateFile "Winter's Bone"
call :CreateFile "Let Me In"
call :CreateFile "Twelve"
call :CreateFile "All You Need Is Love"
call :CreateFile "Barney's Version"
call :CreateFile "Conan"
call :CreateFile "Despicable Me"
call :CreateFile "For Colored Girls"
call :CreateFile "Get Him to the Greek"
call :CreateFile "How Do You Know"
call :CreateFile "He Dies at the End"
call :CreateFile "Kick-Ass"
call :CreateFile "Letters to Juliet"
call :CreateFile "Made in Dagenham"
call :CreateFile "Please Give"
call :CreateFile "Stone"
call :CreateFile "The Company Men"
call :CreateFile "The Twilight Saga Eclipse"
call :CreateFile "Toy Story 3"
call :CreateFile "Aaranya Kaandam"
call :CreateFile "Mumbai Diaries"
call :CreateFile "Four Lions"
call :CreateFile "Predators"
call :CreateFile "Dirty Girl"
call :CreateFile "Harry Potter and the Deathly Hallows Part 1"
call :CreateFile "Knight and Day"
call :CreateFile "Submarine"
call :CreateFile "The Other Guys"
call :CreateFile "30 Minutes or Less"
call :CreateFile "The Adjustment Bureau"
call :CreateFile "Anonymous"
call :CreateFile "Arthur"
call :CreateFile "Bad Teacher"
call :CreateFile "Battle Los Angeles"
call :CreateFile "Body of Proof"
call :CreateFile "Bridesmaids"
call :CreateFile "Cars 2"
call :CreateFile "Cedar Rapids"
call :CreateFile "The Change-Up"
call :CreateFile "Colombiana"
call :CreateFile "Conan the Barbarian"
call :CreateFile "Cowboys and Aliens"
call :CreateFile "Crazy, Stupid, Love."
call :CreateFile "The Descendants"
call :CreateFile "Drive Angry"
call :CreateFile "Drive"
call :CreateFile "The Girl with the Dragon Tattoo"
call :CreateFile "Hall Pass"
call :CreateFile "Hanna"
call :CreateFile "The Help"
call :CreateFile "Horrible Bosses"
call :CreateFile "I Am Number Four"
call :CreateFile "The Ides of March"
call :CreateFile "Jane Eyre"
call :CreateFile "Larry Crowne"
call :CreateFile "Limitless"
call :CreateFile "The Lincoln Lawyer"
call :CreateFile "Machine Gun Preacher"
call :CreateFile "Margaret"
call :CreateFile "Margin Call"
call :CreateFile "Martha Marcy May Marlene"
call :CreateFile "The Mechanic"
call :CreateFile "Midnight in Paris"
call :CreateFile "Moneyball"
call :CreateFile "Monte Carlo"
call :CreateFile "My Week with Marilyn"
call :CreateFile "No Strings Attached"
call :CreateFile "Pariah"
call :CreateFile "Paul"
call :CreateFile "Priest"
call :CreateFile "Red Riding Hood"
call :CreateFile "Rise of the Planet of the Apes"
call :CreateFile "The Roommate"
call :CreateFile "Shameless"
call :CreateFile "Source Code"
call :CreateFile "Super 8"
call :CreateFile "Take Shelter"
call :CreateFile "Thor"
call :CreateFile "Tinker Tailor Soldier Spy"
call :CreateFile "Unknown"
call :CreateFile "War Horse"
call :CreateFile "Warrior"
call :CreateFile "Water for Elephants"
call :CreateFile "Way Back Home"
call :CreateFile "Win Win"
call :CreateFile "Damsels in Distress"
call :CreateFile "Green Lantern"
call :CreateFile "J. Edgar"
call :CreateFile "Sanctum"
call :CreateFile "Scream 4"
call :CreateFile "The Beaver"
call :CreateFile "The Guard"
call :CreateFile "The Smurfs"
call :CreateFile "Tower Heist"
call :CreateFile "We Bought a Zoo"
call :CreateFile "Young Adult"
call :CreateFile "Your Highness"
call :CreateFile "The Best Exotic Marigold Hotel"
call :CreateFile "Butter"
call :CreateFile "Game of Thrones"
call :CreateFile "Bringing Ashley Home"
call :CreateFile "Batman Year One"
call :CreateFile "Dark Games"
call :CreateFile "Green Guys"
call :CreateFile "The Bunker"
call :CreateFile "The Artist"
call :CreateFile "The Cabin in the Woods"
call :CreateFile "The Iron Lady"
call :CreateFile "The Muppets"
call :CreateFile "We Need to Talk About Kevin"
call :CreateFile "A Dangerous Method"
call :CreateFile "American Horror Story"
call :CreateFile "2 Broke Girls"
call :CreateFile "Friends with Benefits"
call :CreateFile "A Separation"
call :CreateFile "Contagion"
call :CreateFile "The Tree of Life"
call :CreateFile "The Adventures of Tintin"
call :CreateFile "Amour"
call :CreateFile "Anna Karenina"
call :CreateFile "Arbitrage"
call :CreateFile "Argo"
call :CreateFile "The Artist and the Model"
call :CreateFile "The Avengers"
call :CreateFile "Beasts of the Southern Wild"
call :CreateFile "The Best Exotic Marigold Hotel Behind the Story Lights, Colours and Smiles"
call :CreateFile "Celeste and Jesse Forever"
call :CreateFile "Christ Complex"
call :CreateFile "Chronicle"
call :CreateFile "The Dark Knight Rises"
call :CreateFile "Django Unchained"
call :CreateFile "Flight"
call :CreateFile "Frankenweenie"
call :CreateFile "Grabbers"
call :CreateFile "Hitchcock"
call :CreateFile "Les Miserables"
call :CreateFile "Life of Pi"
call :CreateFile "Lincoln"
call :CreateFile "Looper"
call :CreateFile "The Master"
call :CreateFile "Men in Black 3"
call :CreateFile "Moonrise Kingdom"
call :CreateFile "Mud"
call :CreateFile "ParaNorman"
call :CreateFile "The Perks of Being a Wallflower"
call :CreateFile "Prometheus"
call :CreateFile "Rise of the Guardians"
call :CreateFile "Rust and Bone"
call :CreateFile "The Sessions"
call :CreateFile "Skyfall"
call :CreateFile "Silver Linings Playbook"
call :CreateFile "Smashed"
call :CreateFile "Snow White and the Huntsman"
call :CreateFile "Space Milkshake"
call :CreateFile "The Hobbit An Unexpected Journey"
call :CreateFile "This Is 40"
call :CreateFile "Hate Crime"
call :CreateFile "Shadow Dancer"
call :CreateFile "Cloud Atlas"
call :CreateFile "The Place Beyond the Pines"
call :CreateFile "Quartet"
call :CreateFile "Seven Psychopaths"
call :CreateFile "Hyde Park on Hudson"
call :CreateFile "John Carter"
call :CreateFile "Nebraska"
call :CreateFile "Promised Land"
call :CreateFile "Spring Breakers"
call :CreateFile "The Lorax"
call :CreateFile "Veep"
call :CreateFile "Wadjda"
call :CreateFile "21 Jump Street"
call :CreateFile "ATM"
call :CreateFile "Gangs of Wasseypur"
call :CreateFile "Good Vibrations"
call :CreateFile "Safe House"
call :CreateFile "End of Watch"
call :CreateFile "Frances Ha"
call :CreateFile "Pitch Perfect"
call :CreateFile "Ruby Sparks"
call :CreateFile "Safety Not Guaranteed"
call :CreateFile "The Hunger Games"
call :CreateFile "12 Years a Slave"
call :CreateFile "42"
call :CreateFile "American Hustle"
call :CreateFile "American Milkshake"
call :CreateFile "The Amityville Asylum"
call :CreateFile "The Bling Ring"
call :CreateFile "The Croods"
call :CreateFile "Dallas Buyers Club"
call :CreateFile "Despicable Me 2"
call :CreateFile "Frozen"
call :CreateFile "Fruitvale Station"
call :CreateFile "Gravity"
call :CreateFile "The Great Gatsby"
call :CreateFile "Her"
call :CreateFile "Kill Your Darlings"
call :CreateFile "Oblivion"
call :CreateFile "Only God Forgives"
call :CreateFile "Rush"
call :CreateFile "Saving Mr. Banks"
call :CreateFile "The Secret Life of Walter Mitty"
call :CreateFile "The Wolf of Wall Street"
call :CreateFile "13-13-13"
call :CreateFile "About Time"
call :CreateFile "After Earth"
call :CreateFile "This Is the End"
call :CreateFile "Under the Skin"
call :CreateFile "White House Down"
call :CreateFile "Labor Day"
call :CreateFile "The Past"
call :CreateFile "The Fifth Estate"
call :CreateFile "All Is Lost"
call :CreateFile "Ender's Game"
call :CreateFile "The Following"
call :CreateFile "Olympus Has Fallen"
call :CreateFile "One Chance"
call :CreateFile "Philomena"
call :CreateFile "Prisoners"
call :CreateFile "The Spectacular Now"
call :CreateFile "Before Midnight"
call :CreateFile "Rushlights"
call :CreateFile "47 Ronin"
call :CreateFile "Elysium"
call :CreateFile "Enough Said"
call :CreateFile "Inside Llewyn Davis"
call :CreateFile "Locke"
call :CreateFile "Lone Survivor"
call :CreateFile "Captain Phillips"
call :CreateFile "Monsters University"
call :CreateFile "The Ouija Experiment"
call :CreateFile "Pacific Rim"
call :CreateFile "Third Person"
call :CreateFile "Texas Chainsaw"
call :CreateFile "Lee Daniels' The Butler"
call :CreateFile "The Way Way Back"
call :CreateFile "The World's End"
call :CreateFile "The Zero Theorem"
call :CreateFile "An Adventure in Space and Time"
call :CreateFile "Bad Words"
call :CreateFile "Blue Jasmine"
call :CreateFile "Blue Ruin"
call :CreateFile "Insidious Chapter 2"
call :CreateFile "The Kings of Summer"
call :CreateFile "Now You See Me"
call :CreateFile "Only Lovers Left Alive"
call :CreateFile "Paradise"
call :CreateFile "Snowpiercer"
call :CreateFile "The Conjuring"
call :CreateFile "The Double"
call :CreateFile "The Purge"
call :CreateFile "Upstream Color"
call :CreateFile "Authors Anonymous"
call :CreateFile "Bad Country"
call :CreateFile "Annabelle"
call :CreateFile "Big Eyes"
call :CreateFile "Birdman or (The Unexpected Virtue of Ignorance)"
call :CreateFile "The Boxtrolls"
call :CreateFile "Boyhood"
call :CreateFile "Fargo"
call :CreateFile "The Fault in Our Stars"
call :CreateFile "Get on Up"
call :CreateFile "How to Train Your Dragon 2"
call :CreateFile "Interstellar"
call :CreateFile "Into the Woods"
call :CreateFile "John Wick"
call :CreateFile "The Lego Movie"
call :CreateFile "The Theory of Everything"
call :CreateFile "As Above, So Below"
call :CreateFile "Tusk"
call :CreateFile "99 Homes"
call :CreateFile "Learning to Drive"
call :CreateFile "Love Me"
call :CreateFile "Testament of Youth"
call :CreateFile "The Babadook"
call :CreateFile "Reasonable Doubt"
call :CreateFile "The Angriest Man in Brooklyn"
call :CreateFile "Calvary"
call :CreateFile "Edge of Tomorrow"
call :CreateFile "Fury"
call :CreateFile "Gone Girl"
call :CreateFile "Inherent Vice"
call :CreateFile "Krampus The Christmas Devil"
call :CreateFile "Noah"
call :CreateFile "Pawn Sacrifice"
call :CreateFile "Remember Me"
call :CreateFile "St. Vincent"
call :CreateFile "The Grand Budapest Hotel"
call :CreateFile "The Interview"
call :CreateFile "The Reason We Are Not Detectives"
call :CreateFile "Unbroken"
call :CreateFile "While We're Young"
call :CreateFile "Whiplash"
call :CreateFile "Divergent"
call :CreateFile "It Follows"
call :CreateFile "Kids in the Hall"
call :CreateFile "The Equalizer"
call :CreateFile "About Alex"
call :CreateFile "Frank Miller's Sin City A Dame to Kill For"
call :CreateFile "Horrible Bosses 2"
call :CreateFile "Infinitely Polar Bear"
call :CreateFile "Kingsman The Secret Service"
call :CreateFile "Lucy"
call :CreateFile "The Gambler"
call :CreateFile "The Guest"
call :CreateFile "The Imitation Game"
call :CreateFile "The Maze Runner"
call :CreateFile "The Rover"
call :CreateFile "Transcendence"
call :CreateFile "Wild Tales"
call :CreateFile "Anomalisa"
call :CreateFile "I'll See You in My Dreams"
call :CreateFile "Beasts of No Nation"
call :CreateFile "White People"
call :CreateFile "Ex Machina"
call :CreateFile "The Martian"
call :CreateFile "Room"
call :CreateFile "Sicario"
call :CreateFile "Star Wars Episode VII - The Force Awakens"
call :CreateFile "Straight Outta Compton"
call :CreateFile "I Smile Back"
call :CreateFile "Jurassic World"
call :CreateFile "The Lady in the Van"
call :CreateFile "Son of Saul"
call :CreateFile "Return to Sender"
call :CreateFile "The Anthropologist"
call :CreateFile "Bridge of Spies"
call :CreateFile "Carol"
call :CreateFile "Eye in the Sky"
call :CreateFile "Grandma"
call :CreateFile "Hardcore Henry"
call :CreateFile "I Saw the Light"
call :CreateFile "Inside Out"
call :CreateFile "Land of Mine"
call :CreateFile "Between Love and Friendship"
call :CreateFile "Maggie's Plan"
call :CreateFile "Me and Earl and the Dying Girl"
call :CreateFile "Miles Ahead"
call :CreateFile "Mississippi Grind"
call :CreateFile "Mistress America"
call :CreateFile "The Silence"
call :CreateFile "Spotlight"
call :CreateFile "Steve Jobs"
call :CreateFile "The Big Short"
call :CreateFile "The Boy Next Door"
call :CreateFile "The Diary of a Teenage Girl"
call :CreateFile "The End of the Tour"
call :CreateFile "Fantastic Four"
call :CreateFile "The Hateful Eight"
call :CreateFile "The Meddler"
call :CreateFile "Trainwreck"
call :CreateFile "Trumbo"
call :CreateFile "Truth"
call :CreateFile "Woman in Gold"
call :CreateFile "One Wild Moment"
call :CreateFile "Concussion"
call :CreateFile "Hotel Transylvania 2"
call :CreateFile "The Expanse"
call :CreateFile "American Ultra"
call :CreateFile "Creed"
call :CreateFile "Crimson Peak"
call :CreateFile "Focus"
call :CreateFile "Green Room"
call :CreateFile "Joy"
call :CreateFile "Martyrs"
call :CreateFile "Mr. Right"
call :CreateFile "Pitch Perfect 2"
call :CreateFile "Pixels"
call :CreateFile "The Danish Girl"
call :CreateFile "The Good Dinosaur"
call :CreateFile "The Lobster"
call :CreateFile "The Man from U.N.C.L.E."
call :CreateFile "Victor Frankenstein"
call :CreateFile "Maudie"
call :CreateFile "Norman"
call :CreateFile "Crouching Tiger, Hidden Dragon Sword of Destiny"
call :CreateFile "Deadpool"
call :CreateFile "La La Land"
call :CreateFile "Little Men"
call :CreateFile "Passengers"
call :CreateFile "Zootopia"
call :CreateFile "10 Cloverfield Lane"
call :CreateFile "Sausage Party"
call :CreateFile "The Boss"
call :CreateFile "Preacher"
call :CreateFile "Branagh Theatre Live Romeo and Juliet"
call :CreateFile "Slash"
call :CreateFile "Hidden Figures"
call :CreateFile "Stranger Things"
call :CreateFile "20th Century Women"
call :CreateFile "His Secret Past"
call :CreateFile "Arrival"
call :CreateFile "The Birth of a Nation"
call :CreateFile "Denial"
call :CreateFile "Equity"
call :CreateFile "Fences"
call :CreateFile "First Man on Mars"
call :CreateFile "Gold"
call :CreateFile "Jackie"
call :CreateFile "Julieta"
call :CreateFile "Last Chance U"
call :CreateFile "Lion"
call :CreateFile "Manchester by the Sea"
call :CreateFile "Moonlight"
call :CreateFile "Pret-a-porter"
call :CreateFile "Punch Drunk Love"
call :CreateFile "Sing Street"
call :CreateFile "Sully"
call :CreateFile "The Comedian"
call :CreateFile "The Founder"
call :CreateFile "The Grand Tour"
call :CreateFile "The Hollars"
call :CreateFile "The Lost City of Z"
call :CreateFile "The Red Turtle"
call :CreateFile "Toni Erdmann"
call :CreateFile "A Death in the Gunj"
call :CreateFile "A Monster Calls"
call :CreateFile "Barry"
call :CreateFile "Dangal"
call :CreateFile "Janice Dickinson"
call :CreateFile "Good Boy"
call :CreateFile "Inferno"
call :CreateFile "Westworld"
call :CreateFile "Batman v Superman Dawn of Justice"
call :CreateFile "Bridget Jones's Baby"
call :CreateFile "Edward 'Eddie the Eagle' Edwards"
call :CreateFile "Free Fire"
call :CreateFile "Hacksaw Ridge"
call :CreateFile "Hail, Caesar!"
call :CreateFile "Hell or High Water"
call :CreateFile "Kubo and the Two Strings"
call :CreateFile "Lights Out"
call :CreateFile "Love"
call :CreateFile "Miss Sloane"
call :CreateFile "My Big Fat Greek Wedding 2"
call :CreateFile "Nocturnal Animals"
call :CreateFile "Why Him?"
call :CreateFile "The Edge of Seventeen"
call :CreateFile "The Girl on the Train"
call :CreateFile "The Nice Guys"
call :CreateFile "The Secret Life of Pets"
call :CreateFile "The Love Witch"
call :CreateFile "The Accountant"
call :CreateFile "Van Helsing"
call :CreateFile "A Fantastic Woman"
call :CreateFile "Breathe"
call :CreateFile "Brigsby Bear"
call :CreateFile "Film Stars Don't Die in Liverpool"
call :CreateFile "Foxtrot"
call :CreateFile "Happy End"
call :CreateFile "Loveless"
call :CreateFile "Mark Felt The Man Who Brought Down the White House"
call :CreateFile "Novitiate"
call :CreateFile "The Leisure Seeker"
call :CreateFile "A Prayer Before Dawn"
call :CreateFile "Beauty and the Beast"
call :CreateFile "The Big Sick"
call :CreateFile "Coco"
call :CreateFile "Custody"
call :CreateFile "Get Out"
call :CreateFile "Guardians of the Galaxy Vol. 2"
call :CreateFile "It"
call :CreateFile "Logan"
call :CreateFile "Thor Ragnarok"
call :CreateFile "War for the Planet of the Apes"
call :CreateFile "Wonder Woman"
call :CreateFile "Last Flag Flying"
call :CreateFile "The Death of Stalin"
call :CreateFile "The Only Living Boy in New York"
call :CreateFile "Baby Driver"
call :CreateFile "Brad's Status"
call :CreateFile "First Reformed"
call :CreateFile "Southern Belle"
call :CreateFile "The Sweetest Christmas"
call :CreateFile "Battle of the Sexes"
call :CreateFile "Brightstar Buzz"
call :CreateFile "Call Me by Your Name"
call :CreateFile "Disobedience"
call :CreateFile "Downsizing"
call :CreateFile "Dunkirk"
call :CreateFile "Elizabeth Blue"
call :CreateFile "Fixed"
call :CreateFile "Get Shorty"
call :CreateFile "I, Tonya"
call :CreateFile "Lady Bird"
call :CreateFile "The Trace We Leave Behind"
call :CreateFile "Mother!"
call :CreateFile "Okja"
call :CreateFile "The Disaster Artist"
call :CreateFile "The Florida Project"
call :CreateFile "The Man Who Invented Christmas"
call :CreateFile "The Meyerowitz Stories"
call :CreateFile "The Night Watchmen"
call :CreateFile "The Post"
call :CreateFile "The Rider"
call :CreateFile "The Shape of Water"
call :CreateFile "The Wife"
call :CreateFile "Three Billboards Outside Ebbing, Missouri"
call :CreateFile "Wonderstruck"
call :CreateFile "Bareilly Ki Barfi"
call :CreateFile "Newton"
call :CreateFile "Ryan Hansen Solves Crimes on Television"
call :CreateFile "Alien Covenant"
call :CreateFile "All the Money in the World"
call :CreateFile "Atomic Blonde"
call :CreateFile "Bright"
call :CreateFile "Darkest Hour"
call :CreateFile "Death Note"
call :CreateFile "First They Killed My Father"
call :CreateFile "Girls Trip"
call :CreateFile "Happy Death Day"
call :CreateFile "I Don't Feel at Home in This World Anymore."
call :CreateFile "Ingrid Goes West"
call :CreateFile "Molly's Game"
call :CreateFile "Mudbound"
call :CreateFile "My Friend Dahmer"
call :CreateFile "Phantom Thread"
call :CreateFile "Pirates of the Caribbean Dead Men Tell No Tales"
call :CreateFile "Roman J. Israel, Esq."
call :CreateFile "Suburbicon"
call :CreateFile "Super Dark Times"
call :CreateFile "The Babysitter"
call :CreateFile "The Beguiled"
call :CreateFile "The Greatest Showman"
call :CreateFile "The Killing of a Sacred Deer"
call :CreateFile "Totem"
call :CreateFile "Victoria and Abdul"
call :CreateFile "Wind River"
call :CreateFile "You Were Never Really Here"
call :CreateFile "Can You Ever Forgive Me?"
call :CreateFile "A Quiet Place"
call :CreateFile "Black Panther"
call :CreateFile "BlacKkKlansman"
call :CreateFile "Halloween"
call :CreateFile "Fahrenheit 451"
call :CreateFile "Robin Hood"
call :CreateFile "The Old Man and the Gun"
call :CreateFile "Tomb Raider"
call :CreateFile "Boy Erased"
call :CreateFile "Eighth Grade"
call :CreateFile "Her Smell"
call :CreateFile "Mary Poppins Returns"
call :CreateFile "Mary Queen of Scots"
call :CreateFile "On the Basis of Sex"
call :CreateFile "Roma"
call :CreateFile "The Sisters Brothers"
call :CreateFile "Nightflyers"
call :CreateFile "Spitfire"
call :CreateFile "22-Jul"
call :CreateFile "All Is True"
call :CreateFile "Capernaum"
call :CreateFile "Cloak and Dagger"
call :CreateFile "Colette"
call :CreateFile "Crazy Rich Asians"
call :CreateFile "Green Book"
call :CreateFile "If Beale Street Could Talk"
call :CreateFile "Maniac"
call :CreateFile "Never Look Away"
call :CreateFile "Rocket Man"
call :CreateFile "Ruben Brandt, Collector"
call :CreateFile "Second Act"
call :CreateFile "Shadow"
call :CreateFile "Spider-Man Into the Spider-Verse"
call :CreateFile "Stan and Ollie"
call :CreateFile "Summer of 84"
call :CreateFile "The Ballad of Buster Scruggs"
call :CreateFile "Malicious"
call :CreateFile "The Front Runner"
call :CreateFile "The Happy Prince"
call :CreateFile "Warning Shot"
call :CreateFile "What They Had"
call :CreateFile "Blockers"
call :CreateFile "A Simple Favor"
call :CreateFile "American Animals"
call :CreateFile "Annihilation"
call :CreateFile "Assassination Nation"
call :CreateFile "Bad Times at the El Royale"
call :CreateFile "Chapter Seven Loud, Fast, and Keep Going"
call :CreateFile "Bird Box"
call :CreateFile "Creed II"
call :CreateFile "Den of Thieves"
call :CreateFile "Game Night"
call :CreateFile "Hereditary"
call :CreateFile "Hold the Dark"
call :CreateFile "I Think We're Alone Now"
call :CreateFile "Kin"
call :CreateFile "Life Itself"
call :CreateFile "Aquaman"
call :CreateFile "Mid90s"
call :CreateFile "Ocean's Eight"
call :CreateFile "Overlord"
call :CreateFile "Ready Player One"
call :CreateFile "Red Sparrow"
call :CreateFile "Searching"
call :CreateFile "Skyscraper"
call :CreateFile "Slender Man"
call :CreateFile "Suspiria"
call :CreateFile "The Meg"
call :CreateFile "The Nun"
call :CreateFile "The Other Side of the Wind"
call :CreateFile "The Predator"
call :CreateFile "The Spy Who Dumped Me"
call :CreateFile "Tully"
call :CreateFile "Under the Silver Lake"
call :CreateFile "Upgrade"
call :CreateFile "Vox Lux"
call :CreateFile "Booksmart"
call :CreateFile "Jojo Rabbit"
call :CreateFile "The Family Man"
call :CreateFile "Joker"
call :CreateFile "Eli"
call :CreateFile "Parasite"
call :CreateFile "Richard Jewell"
call :CreateFile "The Irishman"
call :CreateFile "Triple Frontier"
call :CreateFile "Honey Boy"
call :CreateFile "Little Women"
call :CreateFile "Marriage Story"
call :CreateFile "Midsommar"
call :CreateFile "The Aeronauts"
call :CreateFile "The Farewell"
call :CreateFile "The Last Black Man in San Francisco"
call :CreateFile "The Lighthouse"
call :CreateFile "The Two Popes"
call :CreateFile "Waves"
call :CreateFile "Grand Hotel"
call :CreateFile "Rabid"
call :CreateFile "1917"
call :CreateFile "After the Wedding"
call :CreateFile "Animal Among Us"
call :CreateFile "Avengers Endgame"
call :CreateFile "Frankie"
call :CreateFile "Harriet"
call :CreateFile "Hustlers"
call :CreateFile "Just Mercy"
call :CreateFile "Knives Out"
call :CreateFile "Motherless Brooklyn"
call :CreateFile "Pain and Glory"
call :CreateFile "Queen and Slim"
call :CreateFile "So Pretty"
call :CreateFile "The Peanut Butter Falcon"
call :CreateFile "The Song of Names"
call :CreateFile "Us"
call :CreateFile "Wreck It Ralph"
call :CreateFile "Ad Astra"
call :CreateFile "Brightburn"
call :CreateFile "Crawl"
call :CreateFile "Doctor Sleep"
call :CreateFile "Extremely Wicked, Shockingly Evil and Vile"
call :CreateFile "Fighting with My Family"
call :CreateFile "Lucy in the Sky"
call :CreateFile "Midway"
call :CreateFile "Pet Sematary"
call :CreateFile "Scary Stories to Tell in the Dark"
call :CreateFile "The Lion King"
call :CreateFile "The Sun Is also a Star"
call :CreateFile "Velvet Buzzsaw"
call :CreateFile "War of the Worlds"
call :CreateFile "The Way Back"
call :CreateFile "Cabin in the Woods"
call :CreateFile "Dave"
call :CreateFile "The Reagans"
call :CreateFile "City Hall"
call :CreateFile "Private Lives"
call :CreateFile "Time to Hunt"
call :CreateFile "Bad Boys for Life"
call :CreateFile "Bill and Ted Face the Music"
call :CreateFile "Bloodshot"
call :CreateFile "Downhill"
call :CreateFile "Palm Springs"
call :CreateFile "Raised by Wolves"
call :CreateFile "Tenet"
call :CreateFile "The Grudge"
call :CreateFile "Welcome to Upload"
call :CreateFile "Chaos Walking"
call :CreateFile "Cherry"

echo All text files have been created in %output_dir%
pause