<#
===============================================================================
Script: create_files.ps1

Description:
    Creates empty text files for a predefined list of movie titles. These files
    serve as placeholders during construction of the movie script dataset used
    in the research project.

Purpose:
    During dataset preparation for the paper
    "Hierarchical Ordinal Framework for Automated Movie Censorship Using
    Full-Length Scripts" (IEEE GCAT 2025), standardized filenames were required
    before collecting and organizing screenplay text. This utility automates
    the creation of placeholder files using sanitized movie titles.

Functionality:
    • Creates the output directory if it does not exist.
    • Converts movie titles into valid filenames.
    • Generates one empty .txt file for each movie.
    • Ensures consistent naming throughout the dataset preparation process.

Inputs:
    - List of movie titles.

Outputs:
    - Empty UTF-8 text files named after each movie.

Author:
    Pratik N. Kalamkar
===============================================================================
#>

# Set the output directory
$outputDir = "G:\My Drive\PhDWorks\4_Final_Writing_Papers\05_ConferencePaper_3\dataset\Movie Scripts Corpus kaggle\screenplay_data\data\raw_texts"

# Create directory if it doesn't exist
if (-not (Test-Path -Path $outputDir)) {
    New-Item -ItemType Directory -Path $outputDir | Out-Null
}

# List of all movie titles
$movies = @(
    "The Brothers Bloom",
    "Burn After Reading",
    "Changeling",
    "The Curious Case of Benjamin Button",
    "Deception",
    "Eagle Eye",
    "Frozen River",
    "Hancock",
    "Hellboy II: The Golden Army",
    "How to Lose Friends & Alienate People",
    "Kung Fu Panda",
    "Marley & Me",
    "Max Payne",
    "Milk",
    "Mirrors",
    "The Other Boleyn Girl",
    "Pineapple Express",
    "Rachel Getting Married",
    "Revolutionary Road",
    "RocknRolla",
    "The Ruins",
    "Semi-Pro",
    "Sex and the City",
    "Speed Racer",
    "Synecdoche, New York",
    "Valkyrie",
    "The Visitor",
    "Wanted",
    "While She Was Out",
    "The Wrestler",
    "Yes Man",
    "In Bruges",
    "Indiana Jones and the Kingdom of the Crystal Skull",
    "Sex Drive",
    "Taken",
    "The Burrowers",
    "The Happening",
    "The House Bunny",
    "The Strangers",
    "Iron Man",
    "All God's Children Can Dance",
    "Frost/Nixon",
    "Happy-Go-Lucky",
    "I've Loved You So Long",
    "Luke and Brie Are on a First Date",
    "Street Kings",
    "Untraceable",
    "Vantage Point",
    "Vicky Cristina Barcelona",
    "Breaking Bad",
    "The Incredible Hulk",
    "Ghost Adventures",
    "Solstice",
    "The Dark Knight",
    "The Hurt Locker",
    "The Informers",
    "The Midnight Meat Train",
    "The Reader",
    "The Russell Girl",
    "Edges of Darkness",
    "Body of Lies",
    "Dr. Horrible's Sing-Along Blog",
    "Forgetting Sarah Marshall",
    "Man Overboard",
    "The Middleman",
    "The Suite Life on Deck",
    "WALLÂ·E",
    "Cloverfield",
    "The Mummy: Tomb of the Dragon Emperor",
    "17 Again",
    "2012",
    "500 Days of Summer",
    "District 9",
    "A Serious Man",
    "All About Steve",
    "Amelia",
    "An Education",
    "Angels & Demons",
    "Avatar",
    "The Blind Side",
    "The Boondock Saints II: All Saints Day",
    "The Box",
    "Broken Embraces",
    "Cirque du Freak: The Vampire's Assistant",
    "Coraline",
    "Parks and Recreation",
    "The Damned United",
    "The Human Centipede (First Sequence)",
    "Drag Me to Hell",
    "Extract",
    "Fantastic Mr. Fox",
    "Friday the 13th",
    "Funny People",
    "Gamer",
    "Triangle",
    "G.I. Joe: The Rise of Cobra",
    "The Hangover",
    "He's Just Not That Into You",
    "I Love You Phillip Morris",
    "The Imaginarium of Doctor Parnassus",
    "In the Loop",
    "The Informant!",
    "Inglourious Basterds",
    "The Invention of Lying",
    "Invictus",
    "It's Complicated",
    "Jennifer's Body",
    "The Last Station",
    "Law Abiding Citizen",
    "The Men Who Stare at Goats",
    "Moon",
    "Nine",
    "Ninja Assassin",
    "Observe and Report",
    "Obsessed",
    "Orphan",
    "Pandorum",
    "Precious",
    "The Proposal",
    "Public Enemies",
    "The Road",
    "S. Darko",
    "Sherlock Holmes",
    "The Shift",
    "Millionaire Slumdog",
    "Star Trek",
    "Cougar Town",
    "Surrogates",
    "Terminator Salvation",
    "The Ugly Truth",
    "Up in the Air",
    "Up",
    "Watchmen",
    "The White Ribbon",
    "Whiteout",
    "Year One",
    "3 Idiots",
    "Bright Star",
    "Enter the Void",
    "Night at the Museum: Battle of the Smithsonian",
    "Planet 51",
    "Solitary Man",
    "Solomon Kane",
    "Sorority Row",
    "The Descent: Part 2",
    "The Time Traveler's Wife",
    "The Young Victoria",
    "Under the Mountain",
    "X-Men Origins: Wolverine",
    "After.Life",
    "Vince: The Roommate from Hell",
    "Curse of the Cat People/Glenda and Odessa",
    "I Hope They Serve Beer in Hell",
    "A Perfect Getaway",
    "God's Country, Off Route 9",
    "The Haunting in Connecticut",
    "A Single Man",
    "American Bully",
    "City Island",
    "Crazy Heart",
    "Murderland",
    "Stoked",
    "The Last House on the Left",
    "The Messenger",
    "The Twilight Saga: New Moon",
    "Where the Wild Things Are",
    "Balls Out: Gary the Tennis Coach",
    "Cloudy with a Chance of Meatballs",
    "Harry Potter and the Half-Blood Prince",
    "I Love You, Man",
    "Mr. Nobody",
    "Notorious",
    "Splice",
    "The Fourth Kind",
    "The Hole",
    "The Unborn",
    "Downton Abbey",
    "127 Hours",
    "Resident Evil: Afterlife",
    "The American",
    "The Back-up Plan",
    "Beginners",
    "Black Swan",
    "Blue Valentine",
    "The Book of Eli",
    "The Bounty Hunter",
    "Buried",
    "Burlesque",
    "Clash of the Titans",
    "Date Night",
    "Death at a Funeral",
    "Easy A",
    "Fair Game",
    "The Fighter",
    "Hesher",
    "Hot Tub Time Machine",
    "How to Train Your Dragon",
    "I Spit on Your Grave",
    "Inception",
    "The Kids Are All Right",
    "The King's Speech",
    "Legion",
    "The Losers",
    "Machete",
    "Megamind",
    "The Next Three Days",
    "Remember Me",
    "Scott Pilgrim vs. the World",
    "She's Out of My League",
    "The Social Network",
    "Tamara Drewe",
    "The Tourist",
    "Wall Street: Money Never Sleeps",
    "The Whistleblower",
    "Alice in Wonderland",
    "Animal Kingdom",
    "Diary of a Wimpy Kid",
    "Flipped",
    "It's Kind of a Funny Story",
    "Never Let Me Go",
    "Percy Jackson & the Olympians: The Lightning Thief",
    "Piranha 3D",
    "Prince of Persia: The Sands of Time",
    "Rabbit Hole",
    "RED",
    "Repo Men",
    "Salt",
    "Secretariat",
    "Skyline",
    "The A-Team",
    "The Conspirator",
    "The Crazies",
    "The Debt",
    "The Expendables",
    "The Sorcerer's Apprentice",
    "The Switch",
    "The Town",
    "The Wolfman",
    "Unthinkable",
    "Valentine's Day",
    "Another Year",
    "Dear John",
    "F",
    "Jack Goes Boating",
    "MacGruber",
    "Winter's Bone",
    "Let Me In",
    "Twelve",
    "All You Need Is Love",
    "Barney's Version",
    "Conan",
    "Despicable Me",
    "For Colored Girls",
    "Get Him to the Greek",
    "How Do You Know",
    "He Dies at the End",
    "Kick-Ass",
    "Letters to Juliet",
    "Made in Dagenham",
    "Please Give",
    "Stone",
    "The Company Men",
    "The Twilight Saga: Eclipse",
    "Toy Story 3",
    "Aaranya Kaandam",
    "Mumbai Diaries",
    "Four Lions",
    "Predators",
    "Dirty Girl",
    "Harry Potter and the Deathly Hallows: Part 1",
    "Knight and Day",
    "Submarine",
    "The Other Guys",
    "30 Minutes or Less",
    "The Adjustment Bureau",
    "Anonymous",
    "Arthur",
    "Bad Teacher",
    "Battle Los Angeles",
    "Body of Proof",
    "Bridesmaids",
    "Cars 2",
    "Cedar Rapids",
    "The Change-Up",
    "Colombiana",
    "Conan the Barbarian",
    "Cowboys & Aliens",
    "Crazy, Stupid, Love.",
    "The Descendants",
    "Drive Angry",
    "Drive",
    "The Girl with the Dragon Tattoo",
    "Hall Pass",
    "Hanna",
    "The Help",
    "Horrible Bosses",
    "I Am Number Four",
    "The Ides of March",
    "Jane Eyre",
    "Larry Crowne",
    "Limitless",
    "The Lincoln Lawyer",
    "Machine Gun Preacher",
    "Margaret",
    "Margin Call",
    "Martha Marcy May Marlene",
    "The Mechanic",
    "Midnight in Paris",
    "Moneyball",
    "Monte Carlo",
    "My Week with Marilyn",
    "No Strings Attached",
    "Pariah",
    "Paul",
    "Priest",
    "Red Riding Hood",
    "Rise of the Planet of the Apes",
    "The Roommate",
    "Shameless",
    "Source Code",
    "Super 8",
    "Take Shelter",
    "Thor",
    "Tinker Tailor Soldier Spy",
    "Unknown",
    "War Horse",
    "Warrior",
    "Water for Elephants",
    "Way Back Home",
    "Win Win",
    "Damsels in Distress",
    "Green Lantern",
    "J. Edgar",
    "Sanctum",
    "Scream 4",
    "The Beaver",
    "The Guard",
    "The Smurfs",
    "Tower Heist",
    "We Bought a Zoo",
    "Young Adult",
    "Your Highness",
    "The Best Exotic Marigold Hotel",
    "Butter",
    "Game of Thrones",
    "Bringing Ashley Home",
    "Batman: Year One",
    "Dark Games",
    "Green Guys",
    "The Bunker",
    "The Artist",
    "The Cabin in the Woods",
    "The Iron Lady",
    "The Muppets",
    "We Need to Talk About Kevin",
    "A Dangerous Method",
    "American Horror Story",
    "2 Broke Girls",
    "Friends with Benefits",
    "A Separation",
    "Contagion",
    "The Tree of Life",
    "The Adventures of Tintin",
    "Amour",
    "Anna Karenina",
    "Arbitrage",
    "Argo",
    "The Artist and the Model",
    "The Avengers",
    "Beasts of the Southern Wild",
    "The Best Exotic Marigold Hotel: Behind the Story: Lights, Colours and Smiles",
    "Celeste & Jesse Forever",
    "Christ Complex",
    "Chronicle",
    "The Dark Knight Rises",
    "Django Unchained",
    "Flight",
    "Frankenweenie",
    "Grabbers",
    "Hitchcock",
    "Les MisÃ©rables",
    "Life of Pi",
    "Lincoln",
    "Looper",
    "The Master",
    "Men in Black 3",
    "Moonrise Kingdom",
    "Mud",
    "ParaNorman",
    "The Perks of Being a Wallflower",
    "Prometheus",
    "Rise of the Guardians",
    "Rust and Bone",
    "The Sessions",
    "Skyfall",
    "Silver Linings Playbook",
    "Smashed",
    "Snow White and the Huntsman",
    "Space Milkshake",
    "The Hobbit: An Unexpected Journey",
    "This Is 40",
    "Hate Crime",
    "Shadow Dancer",
    "Cloud Atlas",
    "The Place Beyond the Pines",
    "Quartet",
    "Seven Psychopaths",
    "Hyde Park on Hudson",
    "John Carter",
    "Nebraska",
    "Promised Land",
    "Spring Breakers",
    "The Lorax",
    "Veep",
    "Wadjda",
    "21 Jump Street",
    "ATM",
    "Gangs of Wasseypur",
    "Good Vibrations",
    "Safe House",
    "End of Watch",
    "Frances Ha",
    "Pitch Perfect",
    "Ruby Sparks",
    "Safety Not Guaranteed",
    "The Hunger Games",
    "12 Years a Slave",
    "42",
    "American Hustle",
    "American Milkshake",
    "The Amityville Asylum",
    "The Bling Ring",
    "The Croods",
    "Dallas Buyers Club",
    "Despicable Me 2",
    "Frozen",
    "Fruitvale Station",
    "Gravity",
    "The Great Gatsby",
    "Her",
    "Kill Your Darlings",
    "Oblivion",
    "Only God Forgives",
    "Rush",
    "Saving Mr. Banks",
    "The Secret Life of Walter Mitty",
    "The Wolf of Wall Street",
    "13/13/13",
    "About Time",
    "After Earth",
    "This Is the End",
    "Under the Skin",
    "White House Down",
    "Labor Day",
    "The Past",
    "The Fifth Estate",
    "All Is Lost",
    "Ender's Game",
    "The Following",
    "Olympus Has Fallen",
    "One Chance",
    "Philomena",
    "Prisoners",
    "The Spectacular Now",
    "Before Midnight",
    "Rushlights",
    "47 Ronin",
    "Elysium",
    "Enough Said",
    "Inside Llewyn Davis",
    "Locke",
    "Lone Survivor",
    "Captain Phillips",
    "Monsters University",
    "The Ouija Experiment",
    "Pacific Rim",
    "Third Person",
    "Texas Chainsaw",
    "Lee Daniels' The Butler",
    "The Way Way Back",
    "The World's End",
    "The Zero Theorem",
    "An Adventure in Space and Time",
    "Bad Words",
    "Blue Jasmine",
    "Blue Ruin",
    "Insidious: Chapter 2",
    "The Kings of Summer",
    "Now You See Me",
    "Only Lovers Left Alive",
    "Paradise",
    "Snowpiercer",
    "The Conjuring",
    "The Double",
    "The Purge",
    "Upstream Color",
    "Authors Anonymous",
    "Bad Country",
    "Annabelle",
    "Big Eyes",
    "Birdman or (The Unexpected Virtue of Ignorance)",
    "The Boxtrolls",
    "Boyhood",
    "Fargo",
    "The Fault in Our Stars",
    "Get on Up",
    "How to Train Your Dragon 2",
    "Interstellar",
    "Into the Woods",
    "John Wick",
    "The Lego Movie",
    "The Theory of Everything",
    "As Above, So Below",
    "Tusk",
    "99 Homes",
    "Learning to Drive",
    "Love Me",
    "Testament of Youth",
    "The Babadook",
    "Reasonable Doubt",
    "The Angriest Man in Brooklyn",
    "Calvary",
    "Edge of Tomorrow",
    "Fury",
    "Gone Girl",
    "Inherent Vice",
    "Krampus: The Christmas Devil",
    "Noah",
    "Pawn Sacrifice",
    "Remember Me",
    "St. Vincent",
    "The Grand Budapest Hotel",
    "The Interview",
    "The Reason We Are Not Detectives",
    "Unbroken",
    "While We're Young",
    "Whiplash",
    "Divergent",
    "It Follows",
    "Kids in the Hall",
    "The Equalizer",
    "About Alex",
    "Frank Miller's Sin City: A Dame to Kill For",
    "Horrible Bosses 2",
    "Infinitely Polar Bear",
    "Kingsman: The Secret Service",
    "Lucy",
    "The Gambler",
    "The Guest",
    "The Imitation Game",
    "The Maze Runner",
    "The Rover",
    "Transcendence",
    "Wild Tales",
    "Anomalisa",
    "I'll See You in My Dreams",
    "Beasts of No Nation",
    "White People",
    "Ex Machina",
    "The Martian",
    "Room",
    "Sicario",
    "Star Wars: Episode VII - The Force Awakens",
    "Straight Outta Compton",
    "I Smile Back",
    "Jurassic World",
    "The Lady in the Van",
    "Son of Saul",
    "Return to Sender",
    "The Anthropologist",
    "Bridge of Spies",
    "Carol",
    "Eye in the Sky",
    "Grandma",
    "Hardcore Henry",
    "I Saw the Light",
    "Inside Out",
    "Land of Mine",
    "Between Love and Friendship",
    "Maggie's Plan",
    "Me and Earl and the Dying Girl",
    "Miles Ahead",
    "Mississippi Grind",
    "Mistress America",
    "The Silence",
    "Spotlight",
    "Steve Jobs",
    "The Big Short",
    "The Boy Next Door",
    "The Diary of a Teenage Girl",
    "The End of the Tour",
    "Fantastic Four",
    "The Hateful Eight",
    "The Meddler",
    "Trainwreck",
    "Trumbo",
    "Truth",
    "Woman in Gold",
    "One Wild Moment",
    "Concussion",
    "Hotel Transylvania 2",
    "The Expanse",
    "American Ultra",
    "Creed",
    "Crimson Peak",
    "Focus",
    "Green Room",
    "Joy",
    "Martyrs",
    "Mr. Right",
    "Pitch Perfect 2",
    "Pixels",
    "The Danish Girl",
    "The Good Dinosaur",
    "The Lobster",
    "The Man from U.N.C.L.E.",
    "Victor Frankenstein",
    "Maudie",
    "Norman",
    "Crouching Tiger, Hidden Dragon: Sword of Destiny",
    "Deadpool",
    "La La Land",
    "Little Men",
    "Passengers",
    "Zootopia",
    "10 Cloverfield Lane",
    "Sausage Party",
    "The Boss",
    "Preacher",
    "Branagh Theatre Live: Romeo and Juliet",
    "Slash",
    "Hidden Figures",
    "Stranger Things",
    "20th Century Women",
    "His Secret Past",
    "Arrival",
    "The Birth of a Nation",
    "Denial",
    "Equity",
    "Fences",
    "First Man on Mars",
    "Gold",
    "Jackie",
    "Julieta",
    "Last Chance U",
    "Lion",
    "Manchester by the Sea",
    "Moonlight",
    "PrÃªt-Ã -porter",
    "Punch Drunk Love",
    "Sing Street",
    "Sully",
    "The Comedian",
    "The Founder",
    "The Grand Tour",
    "The Hollars",
    "The Lost City of Z",
    "The Red Turtle",
    "Toni Erdmann",
    "A Death in the Gunj",
    "A Monster Calls",
    "Barry",
    "Dangal",
    "Janice Dickinson",
    "Good Boy",
    "Inferno",
    "Westworld",
    "Batman v Superman: Dawn of Justice",
    "Bridget Jones's Baby",
    "Edward 'Eddie the Eagle' Edwards",
    "Free Fire",
    "Hacksaw Ridge",
    "Hail, Caesar!",
    "Hell or High Water",
    "Kubo and the Two Strings",
    "Lights Out",
    "Love",
    "Miss Sloane",
    "My Big Fat Greek Wedding 2",
    "Nocturnal Animals",
    "Why Him?",
    "The Edge of Seventeen",
    "The Girl on the Train",
    "The Nice Guys",
    "The Secret Life of Pets",
    "The Love Witch",
    "The Accountant",
    "Van Helsing",
    "A Fantastic Woman",
    "Breathe",
    "Brigsby Bear",
    "Film Stars Don't Die in Liverpool",
    "Foxtrot",
    "Happy End",
    "Loveless",
    "Mark Felt: The Man Who Brought Down the White House",
    "Novitiate",
    "The Leisure Seeker",
    "A Prayer Before Dawn",
    "Beauty and the Beast",
    "The Big Sick",
    "Coco",
    "Custody",
    "Get Out",
    "Guardians of the Galaxy Vol. 2",
    "It",
    "Logan",
    "Thor: Ragnarok",
    "War for the Planet of the Apes",
    "Wonder Woman",
    "Last Flag Flying",
    "The Death of Stalin",
    "The Only Living Boy in New York",
    "Baby Driver",
    "Brad's Status",
    "First Reformed",
    "Southern Belle",
    "The Sweetest Christmas",
    "Battle of the Sexes",
    "Brightstar Buzz",
    "Call Me by Your Name",
    "Disobedience",
    "Downsizing",
    "Dunkirk",
    "Elizabeth Blue",
    "Fixed",
    "Get Shorty",
    "I, Tonya",
    "Lady Bird",
    "The Trace We Leave Behind",
    "Mother!",
    "Okja",
    "The Disaster Artist",
    "The Florida Project",
    "The Man Who Invented Christmas",
    "The Meyerowitz Stories",
    "The Night Watchmen",
    "The Post",
    "The Rider",
    "The Shape of Water",
    "The Wife",
    "Three Billboards Outside Ebbing, Missouri",
    "Wonderstruck",
    "Bareilly Ki Barfi",
    "Newton",
    "Ryan Hansen Solves Crimes on Television",
    "Alien: Covenant",
    "All the Money in the World",
    "Atomic Blonde",
    "Bright",
    "Darkest Hour",
    "Death Note",
    "First They Killed My Father",
    "Girls Trip",
    "Happy Death Day",
    "I Don't Feel at Home in This World Anymore.",
    "Ingrid Goes West",
    "Molly's Game",
    "Mudbound",
    "My Friend Dahmer",
    "Phantom Thread",
    "Pirates of the Caribbean: Dead Men Tell No Tales",
    "Roman J. Israel, Esq.",
    "Suburbicon",
    "Super Dark Times",
    "The Babysitter",
    "The Beguiled",
    "The Greatest Showman",
    "The Killing of a Sacred Deer",
    "Totem",
    "Victoria & Abdul",
    "Wind River",
    "You Were Never Really Here",
    "Can You Ever Forgive Me?",
    "A Quiet Place",
    "Black Panther",
    "BlacKkKlansman",
    "Halloween",
    "Fahrenheit 451",
    "Robin Hood",
    "The Old Man & the Gun",
    "Tomb Raider",
    "Boy Erased",
    "Eighth Grade",
    "Her Smell",
    "Mary Poppins Returns",
    "Mary Queen of Scots",
    "On the Basis of Sex",
    "Roma",
    "The Sisters Brothers",
    "Nightflyers",
    "Spitfire",
    "22-Jul",
    "All Is True",
    "Capernaum",
    "Cloak & Dagger",
    "Colette",
    "Crazy Rich Asians",
    "Green Book",
    "If Beale Street Could Talk",
    "Maniac",
    "Never Look Away",
    "Rocket Man",
    "Ruben Brandt, Collector",
    "Second Act",
    "Shadow",
    "Spider-Man: Into the Spider-Verse",
    "Stan & Ollie",
    "Summer of 84",
    "The Ballad of Buster Scruggs",
    "Malicious",
    "The Front Runner",
    "The Happy Prince",
    "Warning Shot",
    "What They Had",
    "Blockers",
    "A Simple Favor",
    "American Animals",
    "Annihilation",
    "Assassination Nation",
    "Bad Times at the El Royale",
    "Chapter Seven: Loud, Fast, and Keep Going",
    "Bird Box",
    "Creed II",
    "Den of Thieves",
    "Game Night",
    "Hereditary",
    "Hold the Dark",
    "I Think We're Alone Now",
    "Kin",
    "Life Itself",
    "Aquaman",
    "Mid90s",
    "Ocean's Eight",
    "Overlord",
    "Ready Player One",
    "Red Sparrow",
    "Searching",
    "Skyscraper",
    "Slender Man",
    "Suspiria",
    "The Meg",
    "The Nun",
    "The Other Side of the Wind",
    "The Predator",
    "The Spy Who Dumped Me",
    "Tully",
    "Under the Silver Lake",
    "Upgrade",
    "Vox Lux",
    "Booksmart",
    "Jojo Rabbit",
    "The Family Man",
    "Joker",
    "Eli",
    "Parasite",
    "Richard Jewell",
    "The Irishman",
    "Triple Frontier",
    "Honey Boy",
    "Little Women",
    "Marriage Story",
    "Midsommar",
    "The Aeronauts",
    "The Farewell",
    "The Last Black Man in San Francisco",
    "The Lighthouse",
    "The Two Popes",
    "Waves",
    "Grand Hotel",
    "Rabid",
    "1917",
    "After the Wedding",
    "Animal Among Us",
    "Avengers: Endgame",
    "Frankie",
    "Harriet",
    "Hustlers",
    "Just Mercy",
    "Knives Out",
    "Motherless Brooklyn",
    "Pain and Glory",
    "Queen & Slim",
    "So Pretty",
    "The Peanut Butter Falcon",
    "The Song of Names",
    "Us",
    "Wreck It Ralph",
    "Ad Astra",
    "Brightburn",
    "Crawl",
    "Doctor Sleep",
    "Extremely Wicked, Shockingly Evil and Vile",
    "Fighting with My Family",
    "Lucy in the Sky",
    "Midway",
    "Pet Sematary",
    "Scary Stories to Tell in the Dark",
    "The Lion King",
    "The Sun Is also a Star",
    "Velvet Buzzsaw",
    "War of the Worlds",
    "The Way Back",
    "Cabin in the Woods",
    "Dave",
    "The Reagans",
    "City Hall",
    "Private Lives",
    "Time to Hunt",
    "Bad Boys for Life",
    "Bill & Ted Face the Music",
    "Bloodshot",
    "Downhill",
    "Palm Springs",
    "Raised by Wolves",
    "Tenet",
    "The Grudge",
    "Welcome to Upload",
    "Chaos Walking",
    "Cherry"
)

# Create empty text files for each movie
foreach ($movie in $movies) {
    # Remove invalid characters from filename
    $invalidChars = [IO.Path]::GetInvalidFileNameChars() -join ''
    $regex = "[{0}]" -f [RegEx]::Escape($invalidChars)
    $safeName = $movie -replace $regex, ""
    
    # Create the file
    $filePath = Join-Path -Path $outputDir -ChildPath "$safeName.txt"
    if (-not (Test-Path -Path $filePath)) {
        New-Item -ItemType File -Path $filePath | Out-Null
    }
}

Write-Host "All text files have been created in $outputDir"